// electron/src/core/sync.ts
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { hasMappingSource, listRules } from './rules';
import { loadConfig, getToolMcpPath } from './config';
import { listMcp, mergeLocalMcp, getServersForScope, McpServersMap } from './mcp';

export interface SyncOptions {
  scope?: 'global' | 'project';
  tool?: string;
}

function stripFrontmatter(content: string): string {
  const lines = content.split('\n');
  let c = 0;
  let i = 0;
  for (; i < lines.length; i++) {
    if (/^---$/.test(lines[i])) {
      c++;
      if (c === 2) { i++; break; }
    }
  }
  return lines.slice(i).join('\n');
}

// 不删用户手放文件：把 out_dir 中**不在预期生成集合**里的项重命名为
// `*.bak`；若同名 .bak 已存在，附加时间戳避免覆盖。返回被备份的 basename 列表。
// - 子目录同样按目录名备份（不再 `fs.rm` 因缺 {recursive:true} 失败而半途崩）
// - 已存在的 `*.bak` 不重复处理
async function safeCleanOutDir(
  outDir: string,
  expectedFiles: Set<string>,
  logger: (msg: string) => void
): Promise<string[]> {
  let entries: string[];
  try {
    entries = await fs.readdir(outDir);
  } catch {
    return [];
  }
  const backedUp: string[] = [];
  for (const f of entries) {
    if (f.endsWith('.bak')) continue;
    if (expectedFiles.has(f)) continue;
    const src = path.join(outDir, f);
    const stat = await fs.lstat(src).catch(() => null);
    if (!stat) continue;

    let bak = path.join(outDir, `${f}.bak`);
    // 避免覆盖已有 .bak：附 ISO 时间戳
    if (await fs.access(bak).then(() => true, () => false)) {
      bak = path.join(outDir, `${f}.${new Date().toISOString().replace(/[:.]/g, '-')}.bak`);
    }
    await fs.rename(src, bak);
    backedUp.push(path.basename(bak));
    logger(
      stat.isDirectory()
        ? `[aiws] 已将非预期目录备份为 ${path.basename(bak)}（原: ${f}/）`
        : `[aiws] 已将非预期文件备份为 ${path.basename(bak)}（原: ${f}）`
    );
  }
  return backedUp;
}

export async function generateRuleFiles(
  root: string,
  tool: 'cursor' | 'trae',
  targetScope?: string
): Promise<{ count: number; backedUp: string[] }> {
  const aiwsDir = path.join(root, '.ai-workspace');
  const ext = tool === 'cursor' ? '.mdc' : '.md';
  const outDir = tool === 'cursor' ? path.join(root, '.cursor', 'rules') : path.join(root, '.trae', 'rules');
  const mappingFile = path.join(aiwsDir, 'adapters', tool, 'mapping.yaml');
  const mapping = await fs.readFile(mappingFile, 'utf8').catch(() => '');

  await fs.mkdir(outDir, { recursive: true });

  const rules = await listRules(root);

  // 第一遍：算出本次会生成的文件名集合，作为白名单
  const expected = new Set<string>();
  for (const rule of rules) {
    if (targetScope === 'global' && rule.domain) continue;
    if (targetScope === 'project' && !rule.domain) continue;
    const rel = rule.domain ? `rules/domains/${rule.id}.md` : `rules/${rule.id}.md`;
    if (!hasMappingSource(mapping, rel)) continue;
    expected.add(`${rule.id}${ext}`);
  }

  // 用白名单 + .bak 备份替代无差别 `rm -f out_dir/*`
  const backedUp = await safeCleanOutDir(outDir, expected, (m) => console.warn(m));

  // 第二遍：生成（writeFile 会覆盖白名单中的同名文件，无需先删）
  let count = 0;
  for (const rule of rules) {
    if (targetScope === 'global' && rule.domain) continue;
    if (targetScope === 'project' && !rule.domain) continue;
    const rel = rule.domain ? `rules/domains/${rule.id}.md` : `rules/${rule.id}.md`;
    if (!hasMappingSource(mapping, rel)) continue;

    const srcFile = path.join(aiwsDir, 'rules', rule.domain ? 'domains' : '', `${rule.id}.md`);
    const content = await fs.readFile(srcFile, 'utf8');
    const description = content.match(/^description:\s*(.+)$/m)?.[1]?.trim()
      ?? content.match(/^title:\s*(.+)$/m)?.[1]?.trim()
      ?? rule.id;
    const scene = tool === 'cursor' && (rule.id === '05-version-control' || rule.id === 'global-workflow')
      ? 'scene: git_message'
      : '';
    // per-tool required:不同工具的 mapping 各持一份
    const required = rule.requiredByTool[tool] ?? false;

    const front = [
      '---',
      '# Generated by AI Workspace - DO NOT EDIT MANUALLY',
      `description: ${description}`,
      `globs: "${rule.globs}"`,
      `alwaysApply: ${required}`,
      scene,
      '---',
    ].filter((l) => l !== '').join('\n');

    const body = stripFrontmatter(content);
    await fs.writeFile(path.join(outDir, `${rule.id}${ext}`), `${front}\n${body}\n`, 'utf8');
    count++;
  }
  return { count, backedUp };
}

function jsonToToml(servers: McpServersMap): string {
  const out: string[] = [];
  for (const [name, s] of Object.entries(servers)) {
    out.push(`[mcp_servers.${name}]`);
    if (s.command) out.push(`command = "${s.command}"`);
    const args = Array.isArray(s.args) ? s.args : [];
    if (args.length) out.push(`args = [${args.map((a: string) => `"${a}"`).join(', ')}]`);
    if (s.url) out.push(`url = "${s.url}"`);
    out.push('');
  }
  return out.join('\n');
}

export async function syncMcpForTool(root: string, tool: string, scope: 'global' | 'project'): Promise<void> {
  const aiwsDir = path.join(root, '.ai-workspace');
  const targetPath = getToolMcpPath(root, tool, scope);
  if (!targetPath) return;
  const base = await listMcp(root).then((list) => {
    const m: McpServersMap = {};
    for (const s of list) { const { name, ...rest } = s; m[name] = rest; }
    return m;
  });
  const local = await fs.readFile(path.join(aiwsDir, 'mcp', 'mcp.local.json'), 'utf8')
    .then((raw) => (JSON.parse(raw).servers ?? {}) as McpServersMap)
    .catch(() => ({} as McpServersMap));
  const merged = mergeLocalMcp(base, local);
  const servers = getServersForScope(merged, scope);
  const clean: McpServersMap = {};
  for (const [name, s] of Object.entries(servers)) {
    const { scope: _scope, ...rest } = s;
    clean[name] = rest;
  }
  if (!Object.keys(clean).length) return;
  const output = tool === 'codex' ? jsonToToml(clean) : JSON.stringify({ mcpServers: clean }, null, 2);
  await fs.mkdir(path.dirname(targetPath), { recursive: true });
  await fs.writeFile(targetPath, output + '\n', 'utf8');
}

export async function* syncRun(root: string, opts: SyncOptions = {}, signal?: AbortSignal): AsyncGenerator<string> {
  yield '开始同步';
  const aiwsDir = path.join(root, '.ai-workspace');
  const cfg = await loadConfig(aiwsDir);
  const tools = opts.tool ? [opts.tool] : cfg.tools;
  const scopes: Array<'global' | 'project'> = opts.scope ? [opts.scope] : ['global', 'project'];

  if (signal?.aborted) return;
  yield '同步规则...';
  for (const tool of tools) {
    if (tool === 'cursor' || tool === 'trae') {
      const { count, backedUp } = await generateRuleFiles(root, tool, opts.scope);
      const tail = backedUp.length ? `，已备份 ${backedUp.length} 个非预期文件` : '';
      yield `已生成 ${tool} 规则 ${count} 个${tail}`;
    } else {
      yield `跳过 ${tool} 规则生成（单文件模式，暂不支持）`;
    }
  }

  if (signal?.aborted) return;
  yield '同步 MCP...';
  for (const tool of tools) {
    for (const scope of scopes) {
      await syncMcpForTool(root, tool, scope);
    }
  }
  yield '同步完成';
}
