// electron/src/core/sync.ts
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { listRules } from './rules';
import { loadConfig, getToolMcpPath } from './config';
import { listMcp, mergeLocalMcp, getServersForScope, McpServersMap } from './mcp';

export interface SyncOptions {
  scope?: 'global' | 'project';
  tool?: string;
}

function stripFrontmatter(content: string): string {
  const lines = content.split('\n');
  let c = 0;
  let i = 0;
  for (; i < lines.length; i++) {
    if (/^---$/.test(lines[i])) {
      c++;
      if (c === 2) { i++; break; }
    }
  }
  return lines.slice(i).join('\n');
}

export async function generateRuleFiles(root: string, tool: 'cursor' | 'trae', targetScope?: string): Promise<{ count: number }> {
  const aiwsDir = path.join(root, '.ai-workspace');
  const ext = tool === 'cursor' ? '.mdc' : '.md';
  const outDir = tool === 'cursor' ? path.join(root, '.cursor', 'rules') : path.join(root, '.trae', 'rules');
  const mappingFile = path.join(aiwsDir, 'adapters', tool, 'mapping.yaml');
  const mapping = await fs.readFile(mappingFile, 'utf8').catch(() => '');

  await fs.mkdir(outDir, { recursive: true });
  for (const f of await fs.readdir(outDir).catch(() => [] as string[])) {
    await fs.rm(path.join(outDir, f), { force: true });
  }

  const rules = await listRules(root);
  let count = 0;
  for (const rule of rules) {
    if (targetScope === 'global' && rule.domain) continue;
    if (targetScope === 'project' && !rule.domain) continue;
    const rel = rule.domain ? `rules/domains/${rule.id}.md` : `rules/${rule.id}.md`;
    if (!mapping.includes(`source: ${rel}`)) continue;

    const srcFile = path.join(aiwsDir, 'rules', rule.domain ? 'domains' : '', `${rule.id}.md`);
    const content = await fs.readFile(srcFile, 'utf8');
    const description = content.match(/^description:\s*(.+)$/m)?.[1]?.trim()
      ?? content.match(/^title:\s*(.+)$/m)?.[1]?.trim()
      ?? rule.id;
    const scene = tool === 'cursor' && (rule.id === '05-version-control' || rule.id === 'global-workflow')
      ? 'scene: git_message'
      : '';

    const front = [
      '---',
      '# Generated by AI Workspace - DO NOT EDIT MANUALLY',
      `description: ${description}`,
      `globs: "${rule.globs}"`,
      `alwaysApply: ${rule.required}`,
      scene,
      '---',
    ].filter((l) => l !== '').join('\n');

    const body = stripFrontmatter(content);
    await fs.writeFile(path.join(outDir, `${rule.id}${ext}`), `${front}\n${body}\n`, 'utf8');
    count++;
  }
  return { count };
}

function jsonToToml(servers: McpServersMap): string {
  const out: string[] = [];
  for (const [name, s] of Object.entries(servers)) {
    out.push(`[mcp_servers.${name}]`);
    if (s.command) out.push(`command = "${s.command}"`);
    if (s.args?.length) out.push(`args = [${s.args.map((a) => `"${a}"`).join(', ')}]`);
    if (s.url) out.push(`url = "${s.url}"`);
    out.push('');
  }
  return out.join('\n');
}

export async function syncMcpForTool(root: string, tool: string, scope: 'global' | 'project'): Promise<void> {
  const aiwsDir = path.join(root, '.ai-workspace');
  const targetPath = getToolMcpPath(root, tool, scope);
  if (!targetPath) return;
  const base = await listMcp(root).then((list) => {
    const m: McpServersMap = {};
    for (const s of list) { const { name, ...rest } = s; m[name] = rest; }
    return m;
  });
  const local = await fs.readFile(path.join(aiwsDir, 'mcp', 'mcp.local.json'), 'utf8')
    .then((raw) => (JSON.parse(raw).servers ?? {}) as McpServersMap)
    .catch(() => ({} as McpServersMap));
  const merged = mergeLocalMcp(base, local);
  const servers = getServersForScope(merged, scope);
  const clean: McpServersMap = {};
  for (const [name, s] of Object.entries(servers)) {
    const { scope: _scope, ...rest } = s;
    clean[name] = rest;
  }
  if (!Object.keys(clean).length) return;
  const output = tool === 'codex' ? jsonToToml(clean) : JSON.stringify({ mcpServers: clean }, null, 2);
  await fs.mkdir(path.dirname(targetPath), { recursive: true });
  await fs.writeFile(targetPath, output + '\n', 'utf8');
}

export async function* syncRun(root: string, opts: SyncOptions = {}, signal?: AbortSignal): AsyncGenerator<string> {
  yield '开始同步';
  const aiwsDir = path.join(root, '.ai-workspace');
  const cfg = await loadConfig(aiwsDir);
  const tools = opts.tool ? [opts.tool] : cfg.tools;
  const scopes: Array<'global' | 'project'> = opts.scope ? [opts.scope] : ['global', 'project'];

  if (signal?.aborted) return;
  yield '同步规则...';
  for (const tool of tools) {
    if (tool === 'cursor' || tool === 'trae') {
      const { count } = await generateRuleFiles(root, tool, opts.scope);
      yield `已生成 ${tool} 规则 ${count} 个`;
    } else {
      yield `跳过 ${tool} 规则生成（单文件模式，暂不支持）`;
    }
  }

  if (signal?.aborted) return;
  yield '同步 MCP...';
  for (const tool of tools) {
    for (const scope of scopes) {
      await syncMcpForTool(root, tool, scope);
    }
  }
  yield '同步完成';
}
