#!/bin/sh
# test-import-rules.sh - import-rules.sh 的单元测试
# 用法: .ai-workspace/scripts/test/test-import-rules.sh
# 独立构造沙盒工作区，不触碰真实仓库。

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LIB_DIR="${SCRIPT_DIR}/../lib"

PASS=0
FAIL=0

t_pass() { PASS=$((PASS + 1)); printf '  ok - %s\n' "$1"; }
t_fail() { FAIL=$((FAIL + 1)); printf '  NOT OK - %s\n' "$1"; }

expect_contains() {
  if grep -qF -- "$2" "$1" 2>/dev/null; then
    t_pass "$3"
  else
    t_fail "$3 (pattern missing: $2)"
  fi
}

expect_absent() {
  if grep -qF -- "$2" "$1" 2>/dev/null; then
    t_fail "$3 (unexpected pattern found: $2)"
  else
    t_pass "$3"
  fi
}

# ============================================================================
# 沙盒工作区构造
# ============================================================================

new_workspace() {
  local ws
  ws="$(mktemp -d "${TMPDIR:-/tmp}/aiws-rules-test.XXXXXX")"
  mkdir -p "$ws/.ai-workspace/rules/domains" \
           "$ws/.ai-workspace/adapters/cursor" \
           "$ws/.ai-workspace/adapters/trae" \
           "$ws/.ai-workspace/adapters/claude" \
           "$ws/.ai-workspace/adapters/codex" \
           "$ws/.cursor/rules" "$ws/.trae/rules"

  # canonical 规则：00-core + 既有 domain 规则 vue（供 exists 分支比对）
  cat > "$ws/.ai-workspace/rules/00-core.md" <<'EOF'
---
id: "00-core"
title: Core
scope: all
description: core rules
---

# Core

- Be explicit.
EOF
  cat > "$ws/.ai-workspace/rules/domains/vue.md" <<'EOF'
---
id: vue
title: Vue
scope: vue
description: vue rules
---

# Vue

- Use Composition API.
EOF
  # 同名但内容不同的 clash 规则（供 conflict 分支比对）
  cat > "$ws/.ai-workspace/rules/domains/clash.md" <<'EOF'
---
id: clash
title: Clash
description: canonical version
---

# Clash

- Canonical body.
EOF

  # 四份 adapter mapping，末尾都是规则列表项（可追加）
  for tool in cursor trae claude codex; do
    cat > "$ws/.ai-workspace/adapters/$tool/mapping.yaml" <<EOF
tool: $tool
version: ">=0.1"
rules:
  - source: rules/00-core.md
    required: true
  - source: rules/domains/vue.md
    required: false
EOF
  done

  echo "$ws"
}

# 规则源文件填充
seed_sources() {
  local ws="$1"

  # AIWS 管理的生成文件 → 应跳过
  cat > "$ws/.cursor/rules/managed.mdc" <<'EOF'
---
# Generated by AI Workspace - DO NOT EDIT MANUALLY
description: managed
globs: "**/*"
alwaysApply: false
---

# Managed
EOF

  # 与 canonical vue 正文一致 → should exist-skip
  cat > "$ws/.cursor/rules/vue.mdc" <<'EOF'
---
description: vue rules
globs: "**/*.vue"
alwaysApply: false
---

# Vue

- Use Composition API.
EOF

  # 手写新规则，带完整 frontmatter → 应导入且字段保留
  cat > "$ws/.cursor/rules/gadgets.mdc" <<'EOF'
---
description: Gadget conventions
globs: "src/gadgets/**"
alwaysApply: true
---

# Gadgets

- Always mock the gadget driver.
EOF

  # 与 clash 同名但正文不同 → conflict 跳过
  cat > "$ws/.cursor/rules/clash.mdc" <<'EOF'
---
description: different version
alwaysApply: false
---

# Clash

- Handwritten divergent body.
EOF

  # 无 frontmatter 的手写 trae 规则 → 整文件作为正文导入
  printf '# Trae Only\n\n- Plain markdown rule.\n' > "$ws/.trae/rules/trrule.md"

  # 带生成标记的手写位置合并文件 → managed 跳过
  {
    echo "<!-- Generated by AI Workspace - DO NOT EDIT MANUALLY -->"
    echo ""
    echo "# Agents generated content"
  } > "$ws/AGENTS.md"

  # 纯手写合并文件 → 配合 --as 导入
  printf '# Project Playbook\n\n- House merge strategy.\n' > "$ws/CLAUDE.md"
}

# 在干净子 shell 中运行 import_rules；AIWS_ROOT 必须指向被测工作区
run_import() {
  local ws="$1"; shift
  (
    export AIWS_ROOT="$ws"
    . "${LIB_DIR}/common.sh" >/dev/null 2>&1
    # common.sh 会把 AIWS_LIB_DIR 推导到沙盒内不存在的路径，
    # 必须显式改指真实 lib 目录
    export AIWS_LIB_DIR="${LIB_DIR}"
    . "${LIB_DIR}/import-rules.sh"
    import_rules "$@"
  )
}

# ============================================================================
# Setup / Teardown
# ============================================================================

WS=""
LOG=""
cleanup() {
  [ -n "$WS" ] && rm -rf "$WS"
  [ -n "$LOG" ] && rm -f "$LOG"
}
trap cleanup EXIT

new_log() {
  LOG="$(mktemp "${TMPDIR:-/tmp}/aiws-rules-log.XXXXXX")"
}

echo "=== import-rules 测试 ==="

# ---------------------------------------------------------------- 1) dry-run 零写入
WS="$(new_workspace)"
seed_sources "$WS"
new_log
run_import "$WS" "" "" 1 1 > "$LOG" 2>&1 || t_fail "dry_run_completes_without_error"
if [ ! -f "$WS/.ai-workspace/rules/domains/gadgets.md" ]; then
  t_pass "dry_run_writes_nothing_new_rule"
else
  t_fail "dry_run_writes_nothing_new_rule"
fi
MAPPING_COUNT=0
for tool in cursor trae claude codex; do
  if grep -qF 'rules/domains/gadgets.md' "$WS/.ai-workspace/adapters/$tool/mapping.yaml" 2>/dev/null; then
    MAPPING_COUNT=$((MAPPING_COUNT + 1))
  fi
done
if [ "$MAPPING_COUNT" = "0" ]; then
  t_pass "dry_run_touches_no_mapping"
else
  t_fail "dry_run_touches_no_mapping"
fi
rm -rf "$WS"; rm -f "$LOG"

# ---------------------------------------------------------------- 2) cursor 导入分类
WS="$(new_workspace)"
seed_sources "$WS"
new_log
run_import "$WS" cursor project 0 1 > "$LOG" 2>&1 || t_fail "cursor_import_exits_zero"

GADGETS="$WS/.ai-workspace/rules/domains/gadgets.md"
# cursor 扫描预期分类：gadgets=new、managed/exists/conflict 各 1
expect_contains "$LOG" "New (will import):     1" "cursor_summary_counts_one_new"
expect_contains "$LOG" "AIWS managed (skip):   1" "cursor_summary_counts_one_managed"
rm -f "$LOG"

# 注：clash 与 canonical 同名不同文 → 归入 conflict，不写入
if [ ! -f "$WS/.ai-workspace/rules/domains/clash.handwritten.md" ]; then
  t_pass "conflict_source_never_written_under_mangled_name"
else
  t_fail "conflict_source_never_written_under_mangled_name"
fi

# 新规则内容转换正确：id/title/globs/description 全部保留
expect_contains "$GADGETS" "id: gadgets" "converted_rule_keeps_id"
expect_contains "$GADGETS" "title: Gadgets" "converted_rule_derives_title_from_h1"
expect_contains "$GADGETS" 'globs: "src/gadgets/**"' "converted_rule_keeps_globs"
expect_contains "$GADGETS" "description: Gadget conventions" "converted_rule_keeps_description"

# managed 跳过：不生成同名 domain 文件
if [ ! -f "$WS/.ai-workspace/rules/domains/managed.md" ]; then
  t_pass "managed_marker_file_skipped"
else
  t_fail "managed_marker_file_skipped"
fi
CANON_VUE_HASH_BEFORE="$(cat "$WS/.ai-workspace/rules/domains/vue.md")"

# ---------------------------------------------------------------- 3) 二次导入幂等收敛
run_import "$WS" cursor project 0 1 > "$LOG" 2>&1 || t_fail "second_run_exits_zero"
expect_contains "$LOG" "Nothing to import." "identical_body_becomes_exists_converges_to_nothing"
for tool in cursor trae claude codex; do
  CNT="$(grep -cF 'rules/domains/gadgets.md' "$WS/.ai-workspace/adapters/$tool/mapping.yaml")"
  if [ "$CNT" = "1" ]; then
    t_pass "mapping_registration_idempotent_${tool}"
  else
    t_fail "mapping_registration_idempotent_${tool} (count=$CNT)"
  fi
done
rm -f "$LOG"

# alwaysApply: true → mapping 登记 required: true
GADGET_REQ="$(awk '/- source: rules\/domains\/gadgets\.md/{found=1; next} found && /required:/{sub(/^[[:space:]]*required:[[:space:]]*/, ""); print; exit}' "$WS/.ai-workspace/adapters/cursor/mapping.yaml")"
if [ "$GADGET_REQ" = "true" ]; then
  t_pass "always_apply_true_registers_required_true"
else
  t_fail "always_apply_true_registers_required_true (got '$GADGET_REQ')"
fi

CANON_VUE_HASH_AFTER="$(cat "$WS/.ai-workspace/rules/domains/vue.md")"
if [ "$CANON_VUE_HASH_BEFORE" = "$CANON_VUE_HASH_AFTER" ]; then
  t_pass "canonical_vue_untouched_by_exists_skip"
else
  t_fail "canonical_vue_untouched_by_exists_skip"
fi
rm -rf "$WS"

# ---------------------------------------------------------------- 4) 合并文件导入与 managed 跳过
WS="$(new_workspace)"
seed_sources "$WS"
new_log
run_import "$WS" codex project 0 1 > "$LOG" 2>&1 || t_fail "codex_merged_managed_only_exits_zero"
expect_contains "$LOG" "AIWS managed (skip):   1" "merged_generated_agents_md_classified_managed"
if [ "$(ls "$WS/.ai-workspace/rules/domains" | wc -l | tr -d ' ')" = "2" ]; then
  t_pass "no_domain_file_created_for_managed_merged"
else
  t_fail "no_domain_file_created_for_managed_merged"
fi
rm -f "$LOG"

new_log
run_import "$WS" claude project 0 1 play-book > "$LOG" 2>&1 || t_fail "claude_as_named_import_exits_zero"
MERGED="$WS/.ai-workspace/rules/domains/play-book.md"
expect_contains "$MERGED" "id: play-book" "as_flag_controls_rule_id"
expect_contains "$MERGED" "title: Project Playbook" "merged_import_keeps_h1_title"
rm -f "$LOG"
rm -rf "$WS"

# ---------------------------------------------------------------- 5) global scope 与非法组合快速失败
WS="$(new_workspace)"
seed_sources "$WS"
new_log
RC=0
run_import "$WS" "" global 1 1 > "$LOG" 2>&1 || RC=$?
if [ "$RC" -ne 0 ]; then
  t_pass "global_scope_rejected_loudly"
else
  t_fail "global_scope_rejected_loudly"
fi

RC=0
run_import "$WS" cursor project 1 1 some-name > "$LOG" 2>&1 || RC=$?
if [ "$RC" -ne 0 ]; then
  t_pass "as_without_merged_tool_rejected"
else
  t_fail "as_without_merged_tool_rejected"
fi
rm -f "$LOG"
rm -rf "$WS"

# ---------------------------------------------------------------- 6) 导入后可被 sync 闭环消费
WS="$(new_workspace)"
seed_sources "$WS"
new_log
run_import "$WS" cursor project 0 1 >/dev/null 2>&1 || t_fail "sync_loop_import_seed"
(
  export AIWS_ROOT="$WS"
  . "${LIB_DIR}/common.sh" >/dev/null 2>&1
  export AIWS_LIB_DIR="${LIB_DIR}"
  . "${LIB_DIR}/rules-generate.sh"
  generate_rule_files cursor "" >/dev/null
  generate_rule_files trae "" >/dev/null
) > "$LOG" 2>&1 || t_fail "sync_after_import_exits_zero"

if [ -f "$WS/.cursor/rules/gadgets.mdc" ] && grep -qF "alwaysApply: true" "$WS/.cursor/rules/gadgets.mdc"; then
  t_pass "synced_cursor_file_carries_always_apply"
else
  t_fail "synced_cursor_file_carries_always_apply"
fi
if [ -f "$WS/.trae/rules/gadgets.md" ]; then
  t_pass "synced_trae_file_created_from_imported_rule"
else
  t_fail "synced_trae_file_created_from_imported_rule"
fi
rm -f "$LOG"
rm -rf "$WS"

# ============================================================================
# Summary
# ============================================================================

echo ""
echo "pass $PASS / fail $FAIL"
[ "$FAIL" -eq 0 ]
