#!/bin/sh
# test-drift-check.sh - drift-check.sh 的单元测试
# 用法: .ai-workspace/scripts/test/test-drift-check.sh
# 独立构造沙盒工作区，不触碰真实仓库。

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LIB_DIR="${SCRIPT_DIR}/../lib"

PASS=0
FAIL=0

t_pass() { PASS=$((PASS + 1)); printf '  ok - %s\n' "$1"; }
t_fail() { FAIL=$((FAIL + 1)); printf '  NOT OK - %s\n' "$1"; }

# 断言：check_drift 返回码精确等于期望值
# 不用宽松的"非零即失败"，否则环境错误(rc=2)会洗白检出用例(rc=1)
assert_rc() {
  local desc="$1" expected="$2"; shift 2
  local rc=0
  run_check "$@" >/dev/null 2>&1 || rc=$?
  if [ "$rc" -eq "$expected" ]; then
    t_pass "$desc"
  else
    t_fail "$desc (expected rc=$expected, got rc=$rc)"
  fi
}

# ============================================================================
# 沙盒工作区构造
# ============================================================================

new_workspace() {
  local ws
  ws="$(mktemp -d "${TMPDIR:-/tmp}/aiws-drift-test.XXXXXX")"
  mkdir -p "$ws/.ai-workspace/rules/domains" \
           "$ws/.ai-workspace/adapters/cursor" \
           "$ws/.ai-workspace/adapters/trae" \
           "$ws/.cursor/rules" "$ws/.trae/rules"

  # 一条 canonical 规则 + 一条 domain 规则
  cat > "$ws/.ai-workspace/rules/00-core.md" <<'EOF'
---
id: "00-core"
title: Core
scope: all
description: core rules
---

# Core

- Be explicit.
EOF
  cat > "$ws/.ai-workspace/rules/domains/vue.md" <<'EOF'
---
id: vue
title: Vue
scope: vue
description: vue rules
---

# Vue

- Use Composition API.
EOF

  # mapping：两条都 required: true
  for tool in cursor trae; do
    cat > "$ws/.ai-workspace/adapters/$tool/mapping.yaml" <<'EOF'
tool: TOOL
version: ">=0.1"
rules:
  - source: rules/00-core.md
    required: true
  - source: rules/domains/vue.md
    required: true
EOF
    sed -i '' "s/TOOL/$tool/" "$ws/.ai-workspace/adapters/$tool/mapping.yaml"
  done

  echo "$ws"
}

# 用真实 sync 语义生成基线（直接调用 generate_rule_files）
sync_baseline() {
  local ws="$1"
  (
    export AIWS_ROOT="$ws"
    . "${LIB_DIR}/common.sh" >/dev/null 2>&1
    . "${LIB_DIR}/rules-generate.sh"
    generate_rule_files cursor "" >/dev/null
    generate_rule_files trae "" >/dev/null
  ) >/dev/null 2>&1
}

# 在干净子 shell 中运行 check_drift；AIWS_ROOT 必须指向被测工作区
run_check() {
  local ws="$1" scope="${2:-}"
  (
    export AIWS_ROOT="$ws"
    . "${LIB_DIR}/common.sh" >/dev/null 2>&1
    # common.sh 会把 AIWS_LIB_DIR 推导到沙盒内不存在的路径，
    # 而沙盒工作区不含 scripts/，必须显式改指真实 lib 目录
    export AIWS_LIB_DIR="${LIB_DIR}"
    . "${LIB_DIR}/drift-check.sh"
    check_drift "$scope"
  )
}

# ============================================================================
# Setup / Teardown
# ============================================================================

WS=""
cleanup() { [ -n "$WS" ] && rm -rf "$WS"; }
trap cleanup EXIT

echo "=== drift-check 测试 ==="

# 1) 完全同步 → rc=0
WS="$(new_workspace)"
sync_baseline "$WS"
assert_rc "check_drift_synced_returns_zero" 0 "$WS"
rm -rf "$WS"

# 2) 规则内容修改后未 sync → rc=1 (stale)
WS="$(new_workspace)"
sync_baseline "$WS"
printf '\n- New rule line.\n' >> "$WS/.ai-workspace/rules/domains/vue.md"
assert_rc "check_drift_detects_stale_body" 1 "$WS"
rm -rf "$WS"

# 3) 删除生成文件 → rc=1 (missing)
WS="$(new_workspace)"
sync_baseline "$WS"
rm "$WS/.trae/rules/vue.md"
assert_rc "check_drift_detects_missing_file" 1 "$WS"
rm -rf "$WS"

# 4) 磁盘多出白名单外文件 → rc=1 (extra)；.bak 不算 → rc=0
WS="$(new_workspace)"
sync_baseline "$WS"
cat > "$WS/.cursor/rules/orphan.mdc" <<'EOF'
---
# Generated by AI Workspace - DO NOT EDIT MANUALLY
description: orphan
globs: "**/*"
alwaysApply: false
---

# Orphan
EOF
assert_rc "check_drift_detects_extra_file" 1 "$WS"
mv "$WS/.cursor/rules/orphan.mdc" "$WS/.cursor/rules/orphan.mdc.bak"
assert_rc "check_drift_ignores_bak_files" 0 "$WS"
rm -rf "$WS"

# 5) 修改 canonical 规则 → rc=1；重新 sync 后 → rc=0（收敛性）
WS="$(new_workspace)"
sync_baseline "$WS"
printf '\n- Drift in canonical.\n' >> "$WS/.ai-workspace/rules/00-core.md"
assert_rc "check_drift_detects_canonical_stale" 1 "$WS"
sync_baseline "$WS"
assert_rc "check_drift_passes_after_resync" 0 "$WS"
rm -rf "$WS"

# 6) 检查是只读的：跑完后磁盘生成文件未被改动
WS="$(new_workspace)"
sync_baseline "$WS"
printf '\n- Unsynced edit.\n' >> "$WS/.ai-workspace/rules/domains/vue.md"
run_check "$WS" >/dev/null 2>&1 || true
if grep -q 'Unsynced edit' "$WS/.trae/rules/vue.md"; then
  t_fail "check_drift_is_readonly_on_disk"
else
  t_pass "check_drift_is_readonly_on_disk"
fi
rm -rf "$WS"

# ============================================================================
# Summary
# ============================================================================

echo ""
echo "pass $PASS / fail $FAIL"
[ "$FAIL" -eq 0 ]
