#!/bin/sh
# import-rules.sh - Reverse import rules from tool files into AI Workspace
# Source this file from aiws: . "${SCRIPT_DIR}/lib/import-rules.sh"
# Requires: common.sh to be sourced first
#
# 设计约束（v1）：
#   1. 一个文件 = 一条规则。手写的 CLAUDE.md / AGENTS.md 整文件导入，不做按 H1 切分。
#   2. 只导入非 AIWS 管理的内容。带生成标记的文件属于漂移问题，交给 validate，直接跳过。
#   3. 导入目标统一为 rules/domains/（工具里的既有规则视为项目特定内容）。
#   4. 同名规则：正文一致 → exists 跳过；不一致 → conflict 列出后跳过，绝不覆盖 canonical。
#   5. 导入成功后向所有已存在的 adapter mapping.yaml 登记，否则下一次 sync 会丢弃新规则。

set -e

RULES_IMPORT_MARKER="Generated by AI Workspace"

# ============================================================================
# 源文件解析 helpers
# ============================================================================

is_aiws_managed_file() {
  head -n 5 "$1" | grep -q "${RULES_IMPORT_MARKER}"
}

# 提取 frontmatter 文本（首对 --- 之间）；无 frontmatter 则输出空
extract_frontmatter() {
  awk 'NR==1 && $0=="---" { in_fm=1; next }
       in_fm && $0=="---" { exit }
       in_fm { print }' "$1"
}

# 提取正文：有 frontmatter 时返回闭合 --- 之后的内容，否则整个文件
extract_rule_body() {
  if [ "$(head -n 1 "$1")" = "---" ]; then
    awk 'BEGIN{c=0} /^---$/{c++; next} c>=2{print}' "$1"
  else
    cat "$1"
  fi
}

# 从 frontmatter 文本里读一个标量字段，去掉引号
fm_field() {
  local fm="$1" key="$2"
  printf '%s\n' "$fm" | sed -n "s/^${key}:[[:space:]]*//p" | head -n1 | tr -d '"'
}

# 取正文中第一个 H1 作为 title
first_h1() {
  awk '/^# /{sub(/^#[[:space:]]*/, ""); print; exit}' "$1"
}

# 规则 id 清洗为 [a-z0-9._-]；结果可能为空，调用方必须校验
sanitize_rule_id() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | sed -e 's/[^a-z0-9._-]/-/g' -e 's/^[.-]*//' -e 's/[.-]*$//'
}

# ============================================================================
# 转换：把源文件变成 canonical 规则
# 回传变量：RULE_ID（清洗后的 id）、REQUIRED_FLAG（mapping 用 required 值）
# ============================================================================

# 组装 canonical 规则文件（frontmatter + 正文）
build_canonical_file() {
  local out="$1" id="$2" title="$3" globs="$4" desc="$5" body_file="$6"

  {
    echo "---"
    echo "id: ${id}"
    echo "title: ${title}"
    [ -n "$globs" ] && echo "globs: \"${globs}\""
    echo "description: ${desc}"
    echo "---"
    cat "$body_file"
  } > "$out"
}

# 从 per-rule 文件（cursor .mdc / trae .md）构造 canonical 规则
# required 对齐 Cursor 的 alwaysApply 语义：true = 常驻装载，false = 按 glob 按需装载
build_per_rule_canonical() {
  local src="$1" out="$2"
  local stem fm desc globs title

  stem="$(basename "$src")"
  stem="${stem%.*}"

  fm="$(extract_frontmatter "$src")"
  desc="$(fm_field "$fm" description)"
  globs="$(fm_field "$fm" globs)"
  case "$(fm_field "$fm" alwaysApply)" in
    true) REQUIRED_FLAG="true" ;;
    *)    REQUIRED_FLAG="false" ;;
  esac

  RULE_ID="$(sanitize_rule_id "$stem")"

  extract_rule_body "$src" > "${out}.body"
  title="$(first_h1 "${out}.body")"
  [ -n "$title" ] || title="$RULE_ID"
  [ -n "$desc" ] || desc="$title"

  build_canonical_file "$out" "$RULE_ID" "$title" "$globs" "$desc" "${out}.body"
}

# 从合并文件（CLAUDE.md / AGENTS.md）整条导入。
# 合并文件没有 alwaysApply 语义，一律登记 required:false，用户可按需在 mapping 中调整。
build_merged_canonical() {
  local src="$1" out="$2" tool="$3"
  local id title

  if [ -n "$AS_NAME" ]; then
    id="$AS_NAME"
  else
    # 缺省用仓库目录名做规则 id；claude/codex 同名时第二份会落入 conflict 分支
    id="$(sanitize_rule_id "$(basename "$AIWS_ROOT")")"
  fi
  RULE_ID="$id"
  REQUIRED_FLAG="false"

  extract_rule_body "$src" > "${out}.body"
  title="$(first_h1 "${out}.body")"
  [ -n "$title" ] || title="$id"

  build_canonical_file "$out" "$id" "$title" "" "Imported from ${tool} $(basename "$src")" "${out}.body"
}

# ============================================================================
# mapping.yaml 登记（幂等）
# REGISTERED_TOOLS: 本次导入实际登记成功的 adapter 清单（供结尾提示用）
# ============================================================================

REGISTERED_TOOLS=""

add_registered_tool() {
  local tool="$1"
  case " ${REGISTERED_TOOLS} " in
    *" ${tool} "*) ;;
    *) REGISTERED_TOOLS="${REGISTERED_TOOLS} ${tool}" ;;
  esac
}

register_mapping_entry() {
  local id="$1" req="$2"
  local rel="rules/domains/${id}.md"
  local source_line="- source: ${rel}"

  for tool in $SUPPORTED_TOOLS; do
    local mapping="${AIWS_DIR}/adapters/${tool}/mapping.yaml"

    if [ ! -f "$mapping" ]; then
      log_debug "No mapping.yaml for ${tool}; skip registration"
      continue
    fi

    if grep -qF "$source_line" "$mapping"; then
      add_registered_tool "$tool"
      continue
    fi

    # 追加必须落在 rules: 列表内部——末行既不是列表项/列表键也不是 rules: 头时拒绝写入
    local last_line
    last_line="$(grep -v '^[[:space:]]*$' "$mapping" | tail -n 1)"
    case "$last_line" in
      *"- source:"*|*"required:"*)
        ;;
      "rules:")
        ;;
      *)
        log_warn "跳过 ${tool} mapping 登记（末尾不是规则列表，请手工检查 ${mapping}）"
        continue
        ;;
    esac

    if [ ! -f "${mapping}.bak" ]; then
      backup_file "$mapping"
    fi

    {
      cat "$mapping"
      printf '%s\n' "  - source: ${rel}"
      printf '%s\n' "    required: ${req}"
    } > "${mapping}.tmp.$$" && mv "${mapping}.tmp.$$" "$mapping"

    add_registered_tool "$tool"

    log_debug "Registered ${rel} -> ${tool} mapping (required: ${req})"
  done
}

# ============================================================================
# 扫描 + 分类
# ENTRIES 每行: type|tool|src_path|rule_id|required_flag|staged_path
# type ∈ managed(跳过) | exists(跳过) | conflict(跳过) | new(待导入)
# ============================================================================

# 检查目标 id 在 workspace 的状态并把分类结果记入 ENTRIES
classify_staged_rule() {
  local tool="$1" src="$2" staged="$3"
  local target

  target="${AIWS_DIR}/rules/domains/${RULE_ID}.md"

  if [ ! -f "$target" ]; then
    printf 'new|%s|%s|%s|%s|%s\n' "$tool" "$src" "$RULE_ID" "$REQUIRED_FLAG" "$staged" >> "$ENTRIES"
    return 0
  fi

  # 与既有 canonical 比较：剔除各自 frontmatter 后比正文
  extract_rule_body "$target" > "$STAGE_DIR/compare.existing"
  if cmp -s "${staged}.body" "$STAGE_DIR/compare.existing"; then
    printf 'exists|%s|%s|%s|%s|%s\n' "$tool" "$src" "$RULE_ID" "$REQUIRED_FLAG" "$staged" >> "$ENTRIES"
  else
    printf 'conflict|%s|%s|%s|%s|%s\n' "$tool" "$src" "$RULE_ID" "" "$staged" >> "$ENTRIES"
  fi
}

# 处理单个来源文件：managed 直接记账；其余先转换暂存再分类
stage_one_source() {
  local tool="$1" src="$2" kind="$3"
  local staged

  if is_aiws_managed_file "$src"; then
    printf 'managed|%s|%s||||\n' "$tool" "$src" >> "$ENTRIES"
    return 0
  fi

  STAGE_IDX=$((STAGE_IDX + 1))
  staged="${STAGE_DIR}/${STAGE_IDX}"

  case "$kind" in
    per_rule) build_per_rule_canonical "$src" "$staged" ;;
    merged)   build_merged_canonical "$src" "$staged" "$tool" ;;
  esac

  if [ -z "$RULE_ID" ]; then
    log_warn "跳过无法生成有效 id 的文件: ${src}"
    return 0
  fi

  classify_staged_rule "$tool" "$src" "$staged"
}

# 扫描单个 tool 的全部规则来源，产出分类 entries
discover_rules_for_tool() {
  local tool="$1" src f

  src="$(get_tool_rules_path "$tool")"

  case "$tool" in
    cursor|trae)
      if [ ! -d "$src" ]; then
        log_debug "Rules directory not found: ${src}"
        return 0
      fi
      log_info "Scanning ${tool}: ${src}"
      case "$tool" in
        cursor) for f in "${src}"/*.mdc;  do [ -f "$f" ] && stage_one_source "$tool" "$f" per_rule; done ;;
        trae)   for f in "${src}"/*.md;   do [ -f "$f" ] && stage_one_source "$tool" "$f" per_rule; done ;;
      esac
      ;;
    claude|codex)
      if [ ! -f "$src" ]; then
        log_debug "Merged rules file not found: ${src}"
        return 0
      fi
      log_info "Scanning ${tool}: ${src}"
      stage_one_source "$tool" "$src" merged
      ;;
  esac
}

# ============================================================================
# 主入口
# Usage: import_rules [from_tool] [scope_filter] [dry_run] [auto_yes] [as_name]
# ============================================================================

import_rules() {
  local from_tool="${1:-}"
  local scope_filter="${2:-}"
  local dry_run="${3:-0}"
  local auto_yes="${4:-0}"
  local as_name="${5:-}"

  echo ""

  AS_NAME=""
  if [ -n "$scope_filter" ] && [ "$scope_filter" != "project" ]; then
    die "import rules 仅支持 project scope（各工具全局规则路径未纳入管理）"
  fi

  if [ -n "$as_name" ]; then
    case "$from_tool" in
      claude|codex) ;;
      *) die "--as 需要与 --from claude 或 --from codex 同用（仅整文件导入适用）" ;;
    esac
    AS_NAME="$(sanitize_rule_id "$as_name")"
    if [ -z "$AS_NAME" ]; then
      die "--as 值清洗后为空，请使用字母/数字/连字符组合"
    fi
  fi

  if [ "$dry_run" = "1" ]; then
    log_info "=== Rules Import (DRY RUN) ==="
  else
    log_info "=== Rules Import ==="
  fi
  echo ""

  local tools tool
  if [ -n "$from_tool" ]; then
    tools="$from_tool"
  else
    tools="$(get_enabled_tools)"
  fi

  # 第一遍扫描的工作区：entries 清单 + 转换结果暂存
  ENTRIES="$(mktemp "${TMPDIR:-/tmp}/aiws-rules-entries.XXXXXX")"
  STAGE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/aiws-rules-stage.XXXXXX")"
  STAGE_IDX=0
  cleanup_import_rules() { rm -rf "$ENTRIES" "$STAGE_DIR"; }
  trap cleanup_import_rules EXIT

  # 第一遍：发现 + 分类
  for tool in $tools; do
    is_supported_tool "$tool" || die "Unknown tool: ${tool}"
    discover_rules_for_tool "$tool"
  done

  # 汇总
  local total_new total_managed total_exists total_conflict
  total_new="$(grep -c '^new|' "$ENTRIES" || true)"
  total_managed="$(grep -c '^managed|' "$ENTRIES" || true)"
  total_exists="$(grep -c '^exists|' "$ENTRIES" || true)"
  total_conflict="$(grep -c '^conflict|' "$ENTRIES" || true)"

  echo ""
  log_info "Import summary:"
  log_info "  ${GREEN}New (will import):${NC}     ${total_new}"
  log_info "  ${YELLOW}AIWS managed (skip):${NC}   ${total_managed}"
  log_info "  ${CYAN}Already identical:${NC}     ${total_exists}"
  log_info "  ${RED}Conflict (skip):${NC}       ${total_conflict}"

  local etype etool esrc eid ereq estaged
  while IFS='|' read -r etype etool esrc eid ereq estaged; do
    [ "$etype" = "conflict" ] || continue
    log_warn "  Conflict: ${eid} <- ${esrc}（同名但内容不同，未覆盖）"
  done < "$ENTRIES"

  if [ "$total_new" -eq 0 ]; then
    log_info "Nothing to import."
    return 0
  fi

  if [ "$dry_run" = "1" ]; then
    log_info "Dry run complete. Run without --dry-run to import."
    return 0
  fi

  if [ "$auto_yes" != "1" ]; then
    printf "Import ${total_new} rule(s)? [y/N] "
    read -r confirm
    case "$confirm" in
      [yY]|[yY][eE][sS]) ;;
      *) log_info "Aborted."; return 0 ;;
    esac
  fi
  echo ""

  # 第二遍：写入第一遍已转换好的暂存副本 + 登记所有 adapter mapping
  local imported_ok=0 imported_fail=0 domains_dir target
  domains_dir="${AIWS_DIR}/rules/domains"
  ensure_dir "$domains_dir"

  while IFS='|' read -r etype etool esrc eid ereq estaged; do
    [ "$etype" = "new" ] || continue
    target="${domains_dir}/${eid}.md"

    if cp "$estaged" "$target"; then
      log_success "  Imported: ${eid} <- ${etool} (${esrc})"
      register_mapping_entry "$eid" "$ereq"
      imported_ok=$((imported_ok + 1))
    else
      log_error "  Failed to import: ${eid} <- ${esrc}"
      imported_fail=$((imported_fail + 1))
    fi
  done < "$ENTRIES"

  echo ""
  log_success "Rules import complete: ${GREEN}${imported_ok} imported${NC}, ${YELLOW}${imported_fail} failed${NC}."
  if [ "$imported_fail" -gt 0 ]; then
    return 1
  fi
  if [ -z "$REGISTERED_TOOLS" ]; then
    log_warn "未找到任何 adapter mapping.yaml——直接运行 'aiws sync' 会丢弃上述规则。"
    log_warn "请先运行 'aiws setup' 补齐映射，或参考已有仓库手工创建 adapters/<tool>/mapping.yaml。"
  fi
  log_info "Run 'aiws sync' to propagate imported rules to all tools."
}
